### PR TITLE
Better manage concurrency while fixing choco

### PR DESCRIPTION
**Pull request by Thilas**
Regularly AU update scripts fails because it can't find some chocolatey cmdlets. I'm not 100% sure but it might be because of how AU `fix_choco` works.

With this change, a mutex ensures that only one job can run `fix_choco`. So potentially no more directory removed while being used.

I also:
- dropped the random waiting time because no longer required
- fix a small bug where `fix_choco` was ran once every 2 days instead of 1 day as mentioned in the code

### CODE REVIEW

**Comment by tunisiano187** [comment]
This won't workk, as you've chaned the function name, but not the call to that function

**Comment by Thilas** [comment]
It does work, I never had this issue again since then. Not sure to understand your comment, what function are you talking about exactly??

**Comment by tunisiano187** [comment]
My bad, i missed a line, sorry

**Comment by corbob** [comment]
@Thilas Thank you for this PR. Last week we released the first release of the module under the Chocolatey Community group under the name Chocolatey AU. As part of the release, we have moved the repository over to a GitFlow layout. Could you rebase your branch on `chocolatey-community/develop` and then point this PR at the `develop` branch?

It is possible that the rebase will have some issues, If you'd like some assistance with getting it pointed at develop, feel free to ping me and I can assist with the commands needed to complete the rebase.

Could you also update the description to include a `Testing` section to outline what testing was done? Bonus points if you're able to add a Pester test that will test this issue.

**Comment by Thilas** [comment]
@corbob, done

**Pull request closed without merging**
